dist: xenial
sudo: required

language: minimal

jobs:
  include:
    - stage: test
      name: "test all Devfiles"
      script:
        - ./scripts/oc-cluster.sh
        - wget https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64
        - chmod +x odo-linux-amd64
        - sudo mv odo-linux-amd64 /usr/local/bin/odo
        - which odo
        - odo login -u developer
        - ./scripts/test.sh
        - odo logout
